version: '3'

services:

  restapi:
    container_name: socal-restapi
    build:
      context: ./restapi
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - ${DEFAULT_PORT}:8081
    restart: always
    networks:
      - teamint_test_case
    command: sh startup.sh
    depends_on:
      - db

  worker-server:
    build:
      context: ./restapi
      dockerfile: Dockerfile
    env_file: .env
    networks:
      - teamint_test_case
    restart: always
    # command: ["celery", "-A", "restapi", "worker", "-l", "debug"]
    command: celery -A restapi worker -l debug

  beat-server:
    build:
      context: ./restapi
      dockerfile: Dockerfile
    env_file: .env
    networks:
      - teamint_test_case
    restart: always
    command: ["celery", "-A", "restapi", "beat", "-l", "debug", "--scheduler", "django_celery_beat.schedulers:DatabaseScheduler"]

  rabbitmq:
      image:
          rabbitmq:3-management-alpine
      env_file: .env
      container_name:
          socal-rabbitmq
      # volumes:
      #   - ./rabbitmqconf/:/opt/rabbitmq/etc/rabbitmq/
      ports:
          - 5672:5672
          - 15672:15672
      networks:
          - teamint_test_case
      restart: always

  db:
    image: postgres
    container_name: postgres
    ports:
      - 5432:5432
    restart: always
    env_file: .env
    networks:
      - teamint_test_case

networks:
  teamint_test_case:
      driver:
          bridge