# Generated by Django 3.2.6 on 2021-08-29 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='enriched',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='extra_info',
            field=models.TextField(blank=True, null=True),
        ),
    ]
